name: obs-node

on:
  push:
    tags:
      - '*'

env:
  GITHUB_USER: Mengli619
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: bash scripts/build.sh all
        shell: bash

      - name: Upload
        run: npm run upload
        shell: bash

      - name: Upload debug symbols to sentry
        run: |
          npm install -g @sentry/cli
          rm -rf symbols && mkdir symbols
          for lib in `find prebuild \( -name "*.node" -o -name "*.dylib" -o -name "*.so" \)`; do
            echo "Generate debug information for $lib"
            dsymutil "$lib" -o "symbols/$lib.dSYM"
          done
          sentry-cli --auth-token ${{ secrets.SENTRY_TOKEN }} upload-dif --org bicbt --project cloudswitcher-desktop symbols
        shell: bash